require 'spec_helper'
require 'islandjs_rails/rails_helpers'

RSpec.describe 'Rails 8 Integration' do
  let(:temp_dir) { create_temp_dir }
  
  before do
    mock_rails_root(temp_dir)
    create_temp_package_json(temp_dir, {
      'react' => '^18.3.1',
      'react-dom' => '^18.3.1'
    })
  end

  describe 'Rails 8 Asset Pipeline Integration' do
    it 'works with Rails 8 asset pipeline structure' do
      # Create Rails 8 asset structure
      builds_dir = File.join(temp_dir, 'app', 'assets', 'builds')
      FileUtils.mkdir_p(builds_dir)
      
      # Create Gemfile for ViteInstaller
      File.write(File.join(temp_dir, 'Gemfile'), "source 'https://rubygems.org'\ngem 'rails'")
      
      # Test UMD partials creation
      IslandjsRails.init!
      partials_dir = File.join(temp_dir, 'app', 'views', 'shared', 'islands')
      
      expect(Dir.exist?(partials_dir)).to be true
    end
    
    it 'generates Rails 8 compatible Vite config' do
      # Create Gemfile for ViteInstaller
      File.write(File.join(temp_dir, 'Gemfile'), "source 'https://rubygems.org'\ngem 'rails'")
      
      IslandjsRails.init!
      vite_path = File.join(temp_dir, 'vite.config.islands.ts')
      
      expect(File.exist?(vite_path)).to be true
      
      content = File.read(vite_path)
      expect(content).to include('islands')
      expect(content).to include('public') # Islands output location
    end
  end

  describe 'Rails 8 Hotwire Integration' do
    let(:view_context) {
      Class.new do
        include IslandjsRails::RailsHelpers
        include ActionView::Helpers::TagHelper
        
        def asset_path(path)
          "/assets/#{path}"
        end
        
        def render(options)
          '<script>UMD content</script>'
        end
        
        private
        def html_escape(value)
          ERB::Util.html_escape(value.to_s)
        end
      end.new
    }
    
    it 'generates Turbo-compatible React components' do
      result = view_context.react_component('TestComponent', { id: 123 })
      
      # Should include Turbo event listeners
      expect(result).to include("addEventListener('turbo:load'")
      expect(result).to include("addEventListener('turbo:before-cache'")
      expect(result).to include("addEventListener('turbo:render'")
      
      # Should use Rails 8 compatible mounting
      expect(result).to include('window.ReactDOM.createRoot')
      expect(result).to include('container._reactRoot')
    end
    
    it 'uses modern namespace convention' do
      result = view_context.react_component('TestComponent', {})
      
      expect(result).to include('window.islandjsRails.TestComponent')
    end
  end

  describe 'Rails 8 Performance Optimizations' do
    it 'minimizes asset pipeline integration' do
      # Islands should not interfere with Rails 8 asset optimizations
      vite_path = File.join(temp_dir, 'vite.config.islands.ts')
      create_temp_vite_config(temp_dir)
      
      IslandjsRails.core.update_vite_externals
      
      content = File.read(vite_path)
      
      # Should preserve Rails 8 optimizations
      expect(content).to include('export default')
      expect(content).to include('external') # Vite uses 'external' not 'externals'
      expect(content).to include('external: []') # No externals added yet
    end
  end

  describe 'Rails 8 Deployment Compatibility' do
    it 'works with Rails 8 deployment patterns' do
      # Test that UMD files are properly structured for Rails 8 deployments
      partials_dir = File.join(temp_dir, 'app', 'views', 'shared', 'islands')
      
      IslandjsRails.core.create_partial_file('react', 'console.log("React");', 'React')
      
      partial_path = File.join(partials_dir, '_react.html.erb')
      expect(File.exist?(partial_path)).to be true
      
      content = File.read(partial_path)
      expect(content).to include('<script type="text/javascript">')
      expect(content).to include('Generated by IslandjsRails')
      expect(content).to include('Global: React')
    end
  end
end 